In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

fake_df = pd.read_csv(
    "/content/drive/MyDrive/truthlens_ai/raw/Fake.csv"
)

true_df = pd.read_csv(
    "/content/drive/MyDrive/truthlens_ai/raw/True.csv"
)

In [ ]:
fake_df.shape
true_df.shape

(21417, 4)

In [ ]:
fake_df.columns

Index(['title', 'text', 'subject', 'date'], dtype='object')

In [ ]:
fake_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  object
 1   text     23481 non-null  object
 2   subject  23481 non-null  object
 3   date     23481 non-null  object
dtypes: object(4)
memory usage: 733.9+ KB

In [ ]:
fake_df.isnull().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [ ]:
fake_df.duplicated().sum()

np.int64(3)

In [ ]:
fake_df.isnull().sum()
true_df.isnull().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [ ]:
print("Fake duplicates:", fake_df.duplicated().sum())
print("True duplicates:", true_df.duplicated().sum())

Fake duplicates: 3
True duplicates: 206

In [ ]:
fake_df = fake_df.drop_duplicates()
true_df = true_df.drop_duplicates()

In [ ]:
print("Fake duplicates:", fake_df.duplicated().sum())
print("True duplicates:", true_df.duplicated().sum())

Fake duplicates: 0
True duplicates: 0

In [ ]:
print("Fake News:", len(fake_df))
print("True News:", len(true_df))

Fake News: 23478
True News: 21211

In [ ]:
fake_df["subject"].value_counts()

subject
News               9050
politics           6838
left-news          4459
Government News    1570
US_News             783
Middle-east         778
Name: count, dtype: int64

In [ ]:
true_df["subject"].value_counts()

subject
politicsNews    11220
worldnews        9991
Name: count, dtype: int64

In [ ]:
fake_df["label"] = 0
true_df["label"] = 1

In [ ]:
import pandas as pd

df = pd.concat([fake_df, true_df], ignore_index=True)

In [ ]:
df.shape

(44689, 5)

In [ ]:
df["label"].value_counts()

label
0    23478
1    21211
Name: count, dtype: int64

In [ ]:
df.to_csv(
    "/content/drive/MyDrive/truthlens_ai/processed/combined_news.csv",
    index=False
)

In [ ]:
fake_df.duplicated().sum()
true_df.duplicated().sum()

fake_df["subject"].value_counts()

true_df["subject"].value_counts()

subject
politicsNews    11220
worldnews        9991
Name: count, dtype: int64

In [ ]:
df["content"] = df["title"] + " " + df["text"]

In [ ]:
df[["content", "label"]].head()

                                             content  label
0   Donald Trump Sends Out Embarrassing New Year’...      0
1   Drunk Bragging Trump Staffer Started Russian ...      0
2   Sheriff David Clarke Becomes An Internet Joke...      0
3   Trump Is So Obsessed He Even Has Obama’s Name...      0
4   Pope Francis Just Called Out Donald Trump Dur...      0

In [ ]:
news_df = df[["content", "label"]]

In [ ]:
news_df.head()

                                             content  label
0   Donald Trump Sends Out Embarrassing New Year’...      0
1   Drunk Bragging Trump Staffer Started Russian ...      0
2   Sheriff David Clarke Becomes An Internet Joke...      0
3   Trump Is So Obsessed He Even Has Obama’s Name...      0
4   Pope Francis Just Called Out Donald Trump Dur...      0

In [ ]:
news_df.shape

(44689, 2)

In [ ]:
news_df.to_csv(
    "/content/drive/MyDrive/truthlens_ai/processed/news_dataset.csv",
    index=False
)

In [ ]:
print(news_df["content"].iloc[0])
print(news_df["content"].iloc[100])
print(news_df["content"].iloc[1000])

 Donald Trump Sends Out Embarrassing New Year’s Eve Message; This is Disturbing Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year,  President Angry Pants tweeted.  2018 will be a great year for America! As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year. 2018 will be a great year for America!  Donald J. Trump (@realDonaldTrump) December 31, 2017Trump s tweet went down about as welll as you d expect.What kind of president sends a New Year s greeting like this despicable, petty, infantile gibberish? Only Trump! His lack of decency won t even allow him to rise above the gutter long enough to wish the American citizens a happy new year!  Bishop Talbert Swan (@TalbertSwan) December 31, 2017no one likes you  Calvin (@calvinstowell) December 31, 2017Your impeachment would make 2018 a great year for America, but I ll also accept regaining control of Congress.  Miranda Yaver (@mirandayaver) December 31, 2017Do you hear yourself talk? When you have to include that many people that hate you you have to wonder? Why do the they all hate me?  Alan Sandoval (@AlanSandoval13) December 31, 2017Who uses the word Haters in a New Years wish??  Marlene (@marlene399) December 31, 2017You can t just say happy new year?  Koren pollitt (@Korencarpenter) December 31, 2017Here s Trump s New Year s Eve tweet from 2016.Happy New Year to all, including to my many enemies and those who have fought me and lost so badly they just don t know what to do. Love!  Donald J. Trump (@realDonaldTrump) December 31, 2016This is nothing new for Trump. He s been doing this for years.Trump has directed messages to his  enemies  and  haters  for New Year s, Easter, Thanksgiving, and the anniversary of 9/11. pic.twitter.com/4FPAe2KypA  Daniel Dale (@ddale8) December 31, 2017Trump s holiday tweets are clearly not presidential.How long did he work at Hallmark before becoming President?  Steven Goodine (@SGoodine) December 31, 2017He s always been like this . . . the only difference is that in the last few years, his filter has been breaking down.  Roy Schulze (@thbthttt) December 31, 2017Who, apart from a teenager uses the term haters?  Wendy (@WendyWhistles) December 31, 2017he s a fucking 5 year old  Who Knows (@rainyday80) December 31, 2017So, to all the people who voted for this a hole thinking he would change once he got into power, you were wrong! 70-year-old men don t change and now he s a year older.Photo by Andrew Burton/Getty Images.
 Watch: Joe Biden Just Wrecked Trump In Six Words And It’s Hilarious Former Vice President Joe Biden was asked on Monday by Matt Lauer on NBC s  Today  to name something specific that Donald Trump has been  doing well. Well, that seems like a trick question since Trump has passed no major legislation and reaches across the aisle only to take shots at Democrats in his Twitter timeline during his morning rage-tweets, so Biden struggled to find something, anything, that Trump has done well since taking office. I think there s a number of things he s doing well. But even the things he s doing well, it s how he does them,  Biden said. It s more the tone of this administration that bothers me,  he continued. With all due respect, you haven t come up with one thing you think he s doing well,  Lauer said. Well, I think he married very well,  Biden joked.Although, Biden didn t mention which of Trump s three marriages he s speaking of. Trump s first marriage to Ivana ended after he had an affair with Marla Maples. Trump went on to marry Maples, then they divorced. Trump is currently married to Melania. All three of Trump s wives are former models. Trump is a former reality show star. But, in all instances, he did marry up, since there is no  down  that Trump hasn t hit yet.After struggling to come up with something, Biden eventually praised Trump s choice of keeping military personnel stationed in the Middle East that was there at the end of the Obama administration.Watch:"What do you think Trump is doing well?""I think he married very well."Joe Biden answers questions on @TODAYshow https://t.co/F6EKxHe64M  NBC News (@NBCNews) November 13, 2017In January, Biden had some advice for Trump.  Grow up, Donald,  Biden said of the 71-year-old man baby.  Grow up. Time to be an adult, you re president. You gotta do something, show us what you have,  Biden added.After speculation of Biden running for president in 2020, he admitted on Monday that he isn t ruling it out, but added he could not accept the nomination if it was given to him right now.Photo by Chip Somodevilla/Getty Images.
 Stunning New Poll Reveals Global Opinion Of Donald Trump, This Is Unprecedented (IMAGES) Donald Trump is doing a horrendous job of raising his historically low approval rating in America, and it looks like he s not doing any better in trying to gain the approval and trust of the rest of the world.Thanks to a new survey by the Pew Research Center, we can now rest assured that the entire world hates Trump just as much as most Americans do. The Pew Research Center surveyed 37 countries, discovering that 74% of respondents stated that when it comes to international affairs, they have ZERO confidence that Trump will respond appropriately or do the right thing.This will be damaging enough to Trump s ego, but it gets even worse for him! Pew Research Center also reported that a similar survey was conducted on former President Barack Obama when he was POTUS, and it produced some VERY different results. That survey revealed that 64% of respondents had complete faith in Obama on international affairs.While the fact that most of the world hates Trump is kind of hysterical, what it has done to America s reputation is quite depressing. The study revealed that America s reputation has declined dramatically since the days of Obama. When respondents were asked how they felt about the U.S., only 49% were favorable since Trump got into the White House, which was a 15% decline from Obama s time   and it s only been a few months. The authors of the survey said: In the eyes of most people surveyed around the world, the White House s new occupant is arrogant, intolerant and even dangerous. Among the positive characteristics tested, his highest rating is for being a strong leader. Fewer believe he is charismatic, well-qualified or cares about ordinary people. Ironically, the only two countries who reported to have more confidence in Trump than Obama were Israel and, you guessed it Russia. In fact, Russia increased 42% thanks to Trump s presidency, which should certainly raise some suspicion.You can check out the findings below:Featured image via Pool / Getty Images

In [ ]:
import re

In [ ]:
def clean_text(text):
    # Convert to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)

    # Remove Twitter handles
    text = re.sub(r'@\w+', '', text)

    # Remove punctuation and special characters
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [ ]:
news_df["clean_content"] = news_df["content"].apply(clean_text)

/tmp/ipykernel_5521/4244065586.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news_df["clean_content"] = news_df["content"].apply(clean_text)

In [ ]:
print("BEFORE:\n")
print(news_df["content"].iloc[0][:1000])

print("\n" + "="*80 + "\n")

print("AFTER:\n")
print(news_df["clean_content"].iloc[0][:1000])

BEFORE:

 Donald Trump Sends Out Embarrassing New Year’s Eve Message; This is Disturbing Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year,  President Angry Pants tweeted.  2018 will be a great year for America! As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year. 2018 will be a great year for America!  Donald J. Trump (@realDonaldTrump) December 31, 2017Trump s tweet went down about as welll as you d expect.What kind of president sends a New Year s greeting like this d

================================================================================

AFTER:

donald trump sends out embarrassing new year s eve message this is disturbing donald trump just couldn t wish all americans a happy new year and leave it at that instead he had to give a shout out to his enemies haters and the very dishonest fake news media the former reality show star had just one job to do and he couldn t do it as our country rapidly grows stronger and smarter i want to wish all of my friends supporters enemies haters and even the very dishonest fake news media a happy and healthy new year president angry pants tweeted will be a great year for america as our country rapidly grows stronger and smarter i want to wish all of my friends supporters enemies haters and even the very dishonest fake news media a happy and healthy new year will be a great year for america donald j trump december trump s tweet went down about as welll as you d expect what kind of president sends a new year s greeting like this despicable petty infantile gibberish only trump his lack of decency

In [ ]:
(news_df["clean_content"].str.len() == 0).sum()

np.int64(9)

In [ ]:
news_df.to_csv(
    "/content/drive/MyDrive/truthlens_ai/processed/clean_news_dataset.csv",
    index=False
)

In [ ]:
news_df.shape

(44689, 3)

In [ ]:
(news_df["clean_content"].str.len() == 0).sum()

np.int64(9)

In [ ]:
news_df["clean_content"].str.len().describe()

count    44680.000000
mean      2455.497851
std       2101.774755
min         22.000000
25%       1265.000000
50%       2186.000000
75%       3065.000000
max      50415.000000
Name: clean_content, dtype: float64